### ISSUE TITLE
Set up Ellie links for all code examples

### ISSUE THREAD

**Issue by supermacro** [supermacro/elm-antd#20]
Beyond being able to view the source code of any demo inside of the component showcase, there is an option to view the demo inside of [Ellie](https://ellie-app.com/).

But this is not yet implemented, and takes you to a blank Ellie app.

### Desired Outcome

- All existing component demos should link to their own Ellie app

**Comment by AliNisarAhmed** [comment]
Hey, I would like to contribute to this project, and I would like to start with this issue.

I am still new to contributing to open source projects, so please guide if I do anything wrong...

**Comment by supermacro** [comment]
Hey @AliNisarAhmed this is great!

Start by forking the project, once you fork, you can then install dependencies and run the showcase application:

```
> cd showcase
> npm install
> npm run dev
```

You should have elm already installed. If not, you can download it from [here](https://guide.elm-lang.org/install/elm.html). 

Now you're ready to start working on this issue :)

Once you're done you can open a pull request to merge your branch from your forked repo into this one!
