### ISSUE TITLE
Add Space page to showcase

### ISSUE THREAD

**Issue by supermacro** [supermacro/elm-antd#24]
There is already an implementation of `Layout`, but I have not taken the time to create a page for it in the showcase. 

### Desired outcome:

- Add a `Space` page to the showcase
- Replicate as much functionality as shown in https://ant.design/components/space/ with the current Elm Antd API

**Comment by joshuanianji** [comment]
I can try to work on this! From the current antd components I think I'll only be able to implement the space example with buttons, though.

**Comment by supermacro** [comment]
Sounds good! By the way, I have a typo in the original issue description. It should say:

"There is already an implementation of `Space`, but ..."

> From the current antd components I think I'll only be able to implement the space example with buttons, though.

That's fine! It's a great start to have the demo page available with at least one example. 

Remember to update the link within "Currently Implemented Components" so that it points to the actual demo page instead of this github issue.

**Comment by joshuanianji** [comment]
Yup, I'll do that!

I also noticed that the original Antd had a default horizontal spacing direction, while we have `Vertical` as the default. If you want to change that, I can include it in my PR.

**Comment by supermacro** [comment]
Oh, that's definitely a mistake I made. I would appreciate adding that fix as well. But For the sake of keeping PR's as small as possible, I would ask that you do that fix in a separate PR.

**Comment by joshuanianji** [comment]
All right, sounds good! I guess that could also boost my hacktoberfest pr count as well lol.
