### ISSUE TITLE
Set default direction of Space to Horizontal

### ISSUE THREAD

**Issue by joshuanianji** [supermacro/elm-antd#54]
I'm still learning about contributing to Open Source projects, so I'm not sure if making an issue for a PR this small is overkill. It seems like creating issues better facilitates bugs, though.

**Is this a bug?**
  The current space component has the default direction set to `Vertical`. In the original Antd library, the default is horizontal.

**Is this a feature request?**
  This is not a feature request.

## Desired Outcome
  The default direction for the Space component will be set to `Horizontal`.

**Comment by supermacro** [comment]
> not sure if making an issue for a PR this small is overkill

I think in this case it's trivial to create an issue since you already have the corresponding fix (#55) ... But in general it never hurts to create an issue to document things and communicate to others about what's going on.
