### ISSUE TITLE
Implement button click animation

### ISSUE THREAD

**Issue by supermacro** [supermacro/elm-antd#8]
See [here](https://imgur.com/a/2jbHxAg) for a demo of the click animation.

The official antd button's have a wave-like animation upon clicking a button. This is something that is missing in the current elm-antd buttons. 

### Desired Outcome:

Implement the button click wave animation.

### demo's / references:

https://webdevtrick.com/pure-css-click-effect/
https://codesandbox.io/s/laughing-ride-v3ot1

**Comment by supermacro** [comment]
https://old.reddit.com/r/css/comments/g5fho5/how_to_create_ants_button_onclick_box_shadow_fade/

**Comment by AliNisarAhmed** [comment]
Hey, I would like to implement this...

**Comment by Orasund** [comment]
I believe there are two approaches:
* Going full Css with animation
* Using Elm to animate

I suggest using the latter (as that seems  to be the approach the elm Community is generally taking). To do so, i suggest using [elm-animator](https://package.elm-lang.org/packages/mdgriffith/elm-animator/latest/)

**Comment by supermacro** [comment]
I would recommend trying to implement in CSS first before trying using elm-animator
